spring:
  application: demo1
 # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/te?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&jdbcCompliantTruncation=false&autoReconnect=true&useSSL=false
    username: root
    password: 1234
